#:schema node_modules/wrangler/config-schema.json
name = "vtp-bluewaters"
compatibility_date = "2024-09-23"
pages_build_output_dir = ".vercel/output/static"
compatibility_flags = ["nodejs_compat"]

[build]
command = "npm run pages:build"

[[d1_databases]]
binding = "DB"
database_name = "vtp-bluewaters-db"
database_id = "your-database-id" # We'll ask user to generate this
